name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # The actions/setup-node@v3 step is useful for general GitHub Actions context,
      # but we will now explicitly define Node.js version for Oryx build using NODE_VERSION env var.
      # This step is still good practice for other potential workflow steps that might need Node.js.
      - name: Use Node.js 20.x (for general workflow context)
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_FIELD_048DEDF10 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - for Vite, this is 'dist'
          github_id_token: ${{ steps.idtoken.outputs.result }}
          # Removed "nvm install" from app_build_command as nvm is not available.
          # We will rely on NODE_VERSION environment variable for Oryx.
          app_build_command: "npm install && npm run build"
          # IMPORTANT: Add NODE_VERSION environment variable to ensure Oryx uses Node.js 20.
          # This is the most reliable way to set Node.js version for Oryx builds.
          # Ensure 'env' is at the same indentation level as 'azure_static_web_apps_api_token', 'action', etc.
          env:
            NODE_VERSION: "20.x"
          # If you had an API, you might also need:
          # api_build_command: "npm install && npm run build"
          # api_location: "api" # Example API folder
          # env:
          #   NODE_VERSION: "20.x" # For API as well
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
